from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, ConfigDict, Field


class RecoveryActionBase(BaseModel):
    session_id: str
    prediction_id: Optional[int] = None
    customer_id: Optional[int] = None
    friction_explanation: str = Field(..., description="Gemini explanation of why friction occurred")
    evidence: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Supporting telemetry evidence / timeline context")
    recommended_action: str = Field(..., description="Strategy recommended (e.g. Chat Support, Voucher, Form Assist)")
    generated_message: str = Field(..., description="Empathetic, personalized customer message generated by Gemini")
    discount_code: Optional[str] = None
    action_status: Optional[str] = "PENDING"


class RecoveryActionCreate(RecoveryActionBase):
    pass


class RecoveryActionUpdate(BaseModel):
    action_status: str = Field(..., description="Updated status: PRESENTED, ACCEPTED, DECLINED, DISMISSED")
    responded_at: Optional[datetime] = None


class RecoveryActionResponse(RecoveryActionBase):
    id: int
    created_at: datetime
    responded_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)
